### ISSUE TITLE
JavaScript is not included

### ISSUE THREAD

**Issue by faritka** [NicolasSiver/nodebb-plugin-ns-likes#1]
Hi,

I followed the Readme and added this line into post.tpl

No change was visible.
Then I also copied the file likes_post.tpl into the theme folder node_modules/nodebb-theme-persona/templates/partials/topic

The like button is shown now, but the button doesn't work because JavaScript is not included.

**Comment by NicolasSiver** [comment]
@faritka did you activate plugin itself?

**Comment by faritka** [comment]
Now as I reactivated it, it works.
