### ISSUE TITLE
Like is also upvoting?

### ISSUE THREAD

**Issue by thadeuszlay** [NicolasSiver/nodebb-plugin-ns-likes#2]
I've got two questions:
1) How come when I "Like" a post, the number of upvotes also increases?

In Persona theme I put the Like-Tag in the post.tpl like this (Like tag before reply button)

`  
<small class="pull-right">

```
    <!-- IMPORT partials/topic/likes_post.tpl -->

    <span class="post-tools">

        <a component="post/reply" href="#" class="no-select <!-- IF !privileges.topics:reply -->hidden<!-- ENDIF !privileges.topics:reply -->">[[topic:reply]]</a>

        <a component="post/quote" href="#" class="no-select <!-- IF !privileges.topics:reply -->hidden<!-- ENDIF !privileges.topics:reply -->">[[topic:quote]]</a>

    </span>
```

` 

In the view it looks like this:
![selection_047](https://cloud.githubusercontent.com/assets/6240670/17647906/6da80848-6204-11e6-81c5-765e8cf5e997.png)

How can I make "Likes" and "Upvoting" be independent of each other?

2) How come the number of people who liked a post don't appear next to the "Like" button?

**Comment by NicolasSiver** [comment]
1. `Likes` uses the same features as upvoting. So you can remove plugin and content still have appropriate reactions. Also, you should not use them (likes and upvote/downvote) in the same time.
2. It should. Also if you click _number_ it will provide you more details.

**Comment by thadeuszlay** [comment]
May I also ask how I get to the additional list?
https://github.com/NicolasSiver/nodebb-plugin-ns-likes/blob/master/screenshot2.png

**Comment by NicolasSiver** [comment]
When you will have many users who liked the content, you will see `N others`, that link will open a detailed list about those _others_.
