### ISSUE TITLE
How to show only 1 like button ?

### ISSUE THREAD

**Issue by lyquocnam** [NicolasSiver/nodebb-plugin-ns-likes#6]
default:
![image](https://user-images.githubusercontent.com/8347826/28047453-4c9b5b72-6614-11e7-8fc0-5cd067093d57.png)
I mean:
![image](https://user-images.githubusercontent.com/8347826/28047460-605b7296-6614-11e7-9420-55fe5e9708d7.png)

I tried to edit on `node_modues/nodebb-plugin-ns-likes/public/templates/partials/topic/likes_post.tpl`
and remove:
```
<button component="ns/likes/toggle" type="button" class="btn btn-default btn-xs ns-likes-toggle <!-- IF posts.upvoted -->liked<!-- ENDIF posts.upvoted -->">
--
  | <!-- IF posts.upvoted -->
  | Unlike
  | <!-- ELSE -->
  | Like
  | <!-- ENDIF posts.upvoted -->
  | </button>
```
and restart nodebb but not success !

**Comment by NicolasSiver** [comment]
It should be one button. You should replace like button with a plugin template, not just to add it.

**Comment by lyquocnam** [comment]
@NicolasSiver i tried remove block code like above, but not work, please show me how to do that @@
