### ISSUE TITLE
No trigger click event

### ISSUE THREAD

**Issue by NormandoHall** [NicolasSiver/nodebb-plugin-ns-likes#7]
Hello.

Sometimes clicking at like heart not work. Inspecting listening events, sometimes click event is not listen.

Using nodeBB 1.12.1, nodejs 11.x, ns_likes: 2.0.0

Thanks!

**Comment by NicolasSiver** [comment]
Hm. Is there a new topic related event in `1.12`?
Currently, all event listening is assigned after `action:topic.loading` and `action:posts.loaded` events.

**Comment by NormandoHall** [comment]
> Hm. Is there a new topic related event in `1.12`?

I don´t know, but happens when I reload the page, then there is no click event attached to heart nor likes counter.

**Comment by NormandoHall** [comment]
Two attached images. The first where there is event listener, and the last without event listener after I reload the page

![image](https://user-images.githubusercontent.com/2943127/56557407-4089e700-6571-11e9-9d17-e1a8747724e7.png)


![image](https://user-images.githubusercontent.com/2943127/56557421-54cde400-6571-11e9-92d1-34b1154c1341.png)

**Comment by NicolasSiver** [comment]
Hm. Interesting. It's definitely related to the version of NodeBB.
I just tested with my NodeBB (1.0.2). It's working well after a page refresh.

**Comment by NormandoHall** [comment]
Yes, I fuzzy remember this issue comes after I upgrade nodeBB to 1.10.x and so on

**Comment by NormandoHall** [comment]
Hi Nicolas. Any chance to fix this in nodebb 1.12.x?

**Comment by NicolasSiver** [comment]
Should be resolved in the next major version - v3

**Comment by NormandoHall** [comment]
@NicolasSiver Thank you so much
